server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/housing_manage?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: root123
  jpa:
    database: mysql
    #配置数据库引擎和字符集
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    #配置自动建表：updata:没有表新建，有表更新操作
    hibernate:
      ddl-auto: update
    #控制台显示建表语句
    show-sql: true
  thymeleaf:
    #关闭模板缓存
    cache: false
cors:
  allowedOrigins: localhost:9001